ALTER TYPE "NotificationType" ADD VALUE 'WITHDRAWAL_REQUESTED';
ALTER TYPE "NotificationType" ADD VALUE 'WITHDRAWAL_COMPLETED';
ALTER TYPE "NotificationType" ADD VALUE 'COURSE_ACTIVATED';
ALTER TYPE "NotificationType" ADD VALUE 'REVIEW_CREATED';
